version: '3'
services:
  db-service:
    platform: linux/x86_64
    image: mysql:8.0.32-debian
    container_name: db-service
    hostname: db-service
    expose:
      - 3306
    volumes:
      - ./database:/docker-entrypoint-initdb.d
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=03092001
      - MYSQL_DATABASE=sudoo
    networks:
      - sudoo-network

  cache-service:
    image: redis:alpine3.18
    container_name: cache-service
    hostname: cache-service
    expose:
      - 6379
    environment:
      - REDIS_PASSWORD=03092001
    networks:
      - sudoo-network

  registry:
    image: sudo248dev/sudoo-registry
    container_name: registry
    hostname: registry
    networks:
      - sudoo-network
    ports:
      - "8761:8761"

  api-gateway:
    image: sudo248dev/sudoo-api-gateway
    container_name: api-gateway
    hostname: api-gateway
    depends_on:
      - registry
    networks:
      - sudoo-network
    ports:
      - "8080:8080"

  storge-service:
    image: sudo248dev/sudoo-storage-service
    container_name: storage-service
    hostname: storage-service
    depends_on:
      - registry
    networks:
      - sudoo-network
    volumes:
      - ./storage-service/uploads/:/app/image-service/uploads/

  auth-service:
    image: sudo248dev/sudoo-auth-service
    container_name: auth-service
    hostname: auth-service
    depends_on:
      - registry
      - db-service
      - user-service
    networks:
      - sudoo-network

  product-service:
    image: sudo248dev/sudoo-product-service
    container_name: product-service
    hostname: product-service
    depends_on:
      - registry
      - db-service
    networks:
      - sudoo-network

  user-service:
    image: sudo248dev/sudoo-user-service
    container_name: user-service
    hostname: user-service
    depends_on:
      - registry
      - db-service
    networks:
      - sudoo-network

  cart-service:
    image: sudo248dev/sudoo-cart-service
    container_name: cart-service
    hostname: cart-service
    depends_on:
      - registry
      - db-service
    networks:
      - sudoo-network

  order-service:
    image: sudo248dev/sudoo-order-service
    container_name: order-service
    hostname: order-service
    depends_on:
      - registry
      - db-service
    networks:
      - sudoo-network

#  notification-service:
#    image: sudo248dev/sudoo-notification-service
#    container_name: notification-service
#    hostname: notification-service
#    depends_on:
#      - registry
#    networks:
#      - sudoo-network

networks:
  sudoo-network:
    external: true

volumes:
  database:
    external: true
  mysql:
    external: true