version: '3'
services:
  nginx-proxy:
    image: nginx
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"

  db-service:
    platform: linux/x86_64
    image: mysql:8.0.32-debian
    container_name: db-service
    hostname: db-service
    expose:
      - 3306
    volumes:
      - ./database:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=03092001
      - MYSQL_DATABASE=sudoo
    networks:
      - sudoo-network
    ports:
      - "3309:3306"

  cache-service:
    image: redis:alpine3.18
    container_name: cache-service
    hostname: cache-service
    expose:
      - 6379
    environment:
      - REDIS_PASSWORD=03092001
    networks:
      - sudoo-network
    ports:
      - "6379:6379"

  registry:
    image: sudo248dev/registry:0.0.1
    container_name: registry
    hostname: registry
    networks:
      - sudoo-network
    ports:
      - "8761:8761"

  api-gateway:
    image: sudo248dev/api-gateway:0.0.1
    container_name: api-gateway
    hostname: api-gateway
    depends_on:
      - registry
    networks:
      - sudoo-network
    ports:
      - "9030:9030"

  storge-service:
    image: sudo248dev/storage-service:0.0.1
    container_name: storage-service
    hostname: storage-service
    depends_on:
      - registry
    networks:
      - sudoo-network
    volumes:
      - ./storage-service/uploads/:/app/image-service/uploads/

  auth-service:
    image: sudo248dev/auth-service:0.0.1
    container_name: auth-service
    hostname: auth-service
    depends_on:
      - registry
      - db-service
      - user-service
    networks:
      - sudoo-network

  product-service:
    image: sudo248dev/product-service:0.0.1
    container_name: product-service
    hostname: product-service
    depends_on:
      - registry
      - db-service
    networks:
      - sudoo-network

  user-service:
    image: sudo248dev/user-service:0.0.1
    container_name: user-service
    hostname: user-service
    depends_on:
      - registry
      - db-service
    networks:
      - sudoo-network

  cart-service:
    image: sudo248dev/cart-service:0.0.1
    container_name: cart-service
    hostname: cart-service
    depends_on:
      - registry
      - db-service
    networks:
      - sudoo-network

  order-service:
    image: sudo248dev/order-service:0.0.1
    container_name: order-service
    hostname: order-service
    depends_on:
      - registry
      - db-service
    networks:
      - sudoo-network

  notification-service:
    image: sudo248dev/notification-service:0.0.1
    container_name: notification-service
    hostname: notification-service
    depends_on:
      - registry
    networks:
      - sudoo-network

networks:
  sudoo-network:
    external: true

volumes:
  database:
    external: true